### ISSUE TITLE
hdfs  JournalNode 安装不上去  1.3.0

### ISSUE THREAD

**Issue by ChewJ404** [dromara/CloudEon#134]
**Describe the bug**
hdfs  安装失败，

**To Reproduce**
JournalNode 安装不上去 

**Environment**
 - CloudEon Version: 1.3.0
 - Java Version: 1.8.0_301-b09
 - OS:  CentOS 8.1
 - Kubernetes:
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:26:59Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}`

**Additional context**
`
2024-01-05 11:23:35,543 WARN org.apache.hadoop.security.authentication.server.AuthenticationFilter: Unable to initialize FileSignerSecretProvider, falling back to use random secrets. Reason: Could not read signature secret file: /home/hadoop/hadoop-http-auth-signature-secret
2024-01-05 11:23:35,545 INFO org.eclipse.jetty.server.handler.ContextHandler: Started o.e.j.s.ServletContextHandler@6d5620ce{logs,/logs,file:///opt/edp/hdfs/log/,AVAILABLE}
2024-01-05 11:23:35,545 INFO org.eclipse.jetty.server.handler.ContextHandler: Started o.e.j.s.ServletContextHandler@21be3395{static,/static,file:///home/hadoop/apache-hadoop/share/hadoop/hdfs/webapps/static/,AVAILABLE}
2024-01-05 11:23:35,563 WARN org.eclipse.jetty.webapp.WebAppContext: Failed startup of context o.e.j.w.WebAppContext@1bae316d{journal,/,file:///home/hadoop/apache-hadoop/share/hadoop/hdfs/webapps/journal/,STOPPED}{file:/home/hadoop/apache-hadoop/share/hadoop/hdfs/webapps/journal}
java.lang.ClassFormatError: Unknown constant tag 74 in class file com/sun/org/apache/xerces/internal/impl/validation/ValidationState
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.<init>(XMLDTDValidator.java:201)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator.<init>(XMLNSDTDValidator.java:104)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.<init>(XML11Configuration.java:567)
	at com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.<init>(XIncludeAwareParserConfiguration.java:130)
	at com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.<init>(XIncludeAwareParserConfiguration.java:91)
	at com.sun.org.apache.xerces.internal.parsers.SAXParser.<init>(SAXParser.java:111)
	at com.sun.org.apache.xerces.internal.parsers.SAXParser.<init>(SAXParser.java:96)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.<init>(SAXParserImpl.java:406)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.<init>(SAXParserImpl.java:135)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.newSAXParser(SAXParserFactoryImpl.java:79)
	at org.eclipse.jetty.xml.XmlParser.setValidating(XmlParser.java:90)
	at org.eclipse.jetty.xml.XmlParser.<init>(XmlParser.java:81)
	at org.eclipse.jetty.webapp.WebDescriptor$1.<init>(WebDescriptor.java:70)
	at org.eclipse.jetty.webapp.WebDescriptor.newParser(WebDescriptor.java:69)
	at org.eclipse.jetty.webapp.WebDescriptor.ensureParser(WebDescriptor.java:58)
	at org.eclipse.jetty.webapp.Descriptor.parse(Descriptor.java:52)
	at org.eclipse.jetty.webapp.WebDescriptor.parse(WebDescriptor.java:213)
	at org.eclipse.jetty.webapp.MetaData.setWebXml(MetaData.java:193)
	at org.eclipse.jetty.webapp.WebXmlConfiguration.preConfigure(WebXmlConfiguration.java:55)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:1276)
	at org.apache.hadoop.hdfs.qjournal.server.JournalNodeHttpServer.start(JournalNodeHttpServer.java:86)
	at org.apache.hadoop.hdfs.qjournal.server.JournalNode.start(JournalNode.java:238)
	at org.apache.hadoop.hdfs.qjournal.server.JournalNode.run(JournalNode.java:209)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:95)
	at org.apache.hadoop.hdfs.qjournal.server.JournalNode.main(JournalNode.java:437)
2024-01-05 11:23:35,568 INFO org.eclipse.jetty.server.AbstractConnector: Started ServerConnector@51bd8b5c{HTTP/1.1, (http/1.1)}{0.0.0.0:8480}
2024-01-05 11:23:35,568 INFO org.eclipse.jetty.server.Server: Started @2349ms
2024-01-05 11:23:35,571 INFO org.eclipse.jetty.server.AbstractConnector: Stopped ServerConnector@51bd8b5c{HTTP/1.1, (http/1.1)}{0.0.0.0:8480}
2024-01-05 11:23:35,571 INFO org.eclipse.jetty.server.session: node0 Stopped scavenging
2024-01-05 11:23:35,571 INFO org.eclipse.jetty.server.handler.ContextHandler: Stopped o.e.j.w.WebAppContext@1bae316d{journal,/,null,STOPPED}{file:/home/hadoop/apache-hadoop/share/hadoop/hdfs/webapps/journal}
2024-01-05 11:23:35,572 INFO org.eclipse.jetty.server.handler.ContextHandler: Stopped o.e.j.s.ServletContextHandler@21be3395{static,/static,file:///home/hadoop/apache-hadoop/share/hadoop/hdfs/webapps/static/,STOPPED}
2024-01-05 11:23:35,572 INFO org.eclipse.jetty.server.handler.ContextHandler: Stopped o.e.j.s.ServletContextHandler@6d5620ce{logs,/logs,file:///opt/edp/hdfs/log/,STOPPED}
2024-01-05 11:23:35,572 ERROR org.apache.hadoop.hdfs.qjournal.server.JournalNode: Failed to start JournalNode.
java.io.IOException: Unable to initialize WebAppContext
	at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:1303)
	at org.apache.hadoop.hdfs.qjournal.server.JournalNodeHttpServer.start(JournalNodeHttpServer.java:86)
	at org.apache.hadoop.hdfs.qjournal.server.JournalNode.start(JournalNode.java:238)
	at org.apache.hadoop.hdfs.qjournal.server.JournalNode.run(JournalNode.java:209)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:95)
	at org.apache.hadoop.hdfs.qjournal.server.JournalNode.main(JournalNode.java:437)
Caused by: java.lang.ClassFormatError: Unknown constant tag 74 in class file com/sun/org/apache/xerces/internal/impl/validation/ValidationState
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.<init>(XMLDTDValidator.java:201)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLNSDTDValidator.<init>(XMLNSDTDValidator.java:104)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.<init>(XML11Configuration.java:567)
	at com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.<init>(XIncludeAwareParserConfiguration.java:130)
	at com.sun.org.apache.xerces.internal.parsers.XIncludeAwareParserConfiguration.<init>(XIncludeAwareParserConfiguration.java:91)
	at com.sun.org.apache.xerces.internal.parsers.SAXParser.<init>(SAXParser.java:111)
	at com.sun.org.apache.xerces.internal.parsers.SAXParser.<init>(SAXParser.java:96)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.<init>(SAXParserImpl.java:406)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.<init>(SAXParserImpl.java:135)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.newSAXParser(SAXParserFactoryImpl.java:79)
	at org.eclipse.jetty.xml.XmlParser.setValidating(XmlParser.java:90)
	at org.eclipse.jetty.xml.XmlParser.<init>(XmlParser.java:81)
	at org.eclipse.jetty.webapp.WebDescriptor$1.<init>(WebDescriptor.java:70)
	at org.eclipse.jetty.webapp.WebDescriptor.newParser(WebDescriptor.java:69)
	at org.eclipse.jetty.webapp.WebDescriptor.ensureParser(WebDescriptor.java:58)
	at org.eclipse.jetty.webapp.Descriptor.parse(Descriptor.java:52)
	at org.eclipse.jetty.webapp.WebDescriptor.parse(WebDescriptor.java:213)
	at org.eclipse.jetty.webapp.MetaData.setWebXml(MetaData.java:193)
	at org.eclipse.jetty.webapp.WebXmlConfiguration.preConfigure(WebXmlConfiguration.java:55)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:1276)
	... 6 more
2024-01-05 11:23:35,573 INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: Stopping JournalNode metrics system...
2024-01-05 11:23:35,573 INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: JournalNode metrics system stopped.
2024-01-05 11:23:35,573 INFO org.apache.hadoop.metrics2.impl.MetricsSystemImpl: JournalNode metrics system shutdown complete.
`

**Comment by stdnt-xiao** [comment]
检查一下是否文件权限的问题
Could not read signature secret file: /home/hadoop/hadoop-http-auth-signature-secret
