### ISSUE TITLE
在安装zookeeper的过程中一直卡在一个地方

### ISSUE THREAD

**Issue by KONEONE** [dromara/CloudEon#136]
## Question

Before asking a question, make sure you have（在提问之前，请确保你已经）:

- Read documentation（仔细阅读了官方文档）
- Googled your question（百度搜索了你的问题）
- Searched open and closed GitHub issues（搜索了开放和关闭的 GitHub issues）

Please pay attention on issues you submitted, because we maybe need more details. 

一直卡在这里：
```shell
StartRoleK8sDeploymentTask 144: 在k8s上启动deployment: zookeeper-server-zookeeper ,使用本地资源文件: /home/kone/software/work_env/cloudeon/cloudeon/work/k8s-resource/zookeeper/zookeeper-server.yaml ,持续等待 20 分钟
````

**Comment by KONEONE** [comment]
成功报错：
```shell


2024-01-19 14:17:48,224 INFO o.d.c.p.StartRoleK8sDeploymentTask 127: 完成角色k8s资源文件生成：/home/kone/software/work_env/cloudeon/cloudeon/work/k8s-resource/zookeeper/zookeeper-server.yaml
2024-01-19 14:17:48,372 INFO o.d.c.p.StartRoleK8sDeploymentTask 144: 在k8s上启动deployment: zookeeper-server-zookeeper ,使用本地资源文件: /home/kone/software/work_env/cloudeon/cloudeon/work/k8s-resource/zookeeper/zookeeper-server.yaml ,持续等待 20 分钟
2024-01-19 14:37:48,462 ERROR o.d.c.p.StartRoleK8sDeploymentTask 113: CommandTask:334发生异常，处理异常。。。Timed out waiting for [1200000] milliseconds for [Deployment] with name:[zookeeper-server-zookeeper] in namespace [default].
io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [1200000] milliseconds for [Deployment] with name:[zookeeper-server-zookeeper] in namespace [default].
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilCondition(BaseOperation.java:891)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilReady(BaseOperation.java:875)
	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.waitUntilReady(BaseOperation.java:93)
	at org.dromara.cloudeon.processor.StartRoleK8sDeploymentTask.internalExecute(StartRoleK8sDeploymentTask.java:145)
	at org.dromara.cloudeon.processor.BaseCloudeonTask.run(BaseCloudeonTask.java:79)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)


```

**Comment by KONEONE** [comment]
<font color=red>解决办法：</font>

**Comment by seedsunrise1** [comment]
> **解决办法**
> 
> 这是我的解决办法 在我的所有节点中（包括master节点）的/etc/hosts的DNS映射文件中包含如下的地址映射
> 
> ```
> 127.0.1.1 your_host_name your_host_name
> ```
> 
> 我把它修改为如下，就解决了这个问题
> 
> ```
> 127.0.1.1
> ```
> 
> 感谢，这位群友： ![image](https://private-user-images.githubusercontent.com/39909636/298081676-e4102119-d187-4ab5-829a-a5269478ddcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTA4NzAsIm5iZiI6MTcxMzE1MDU3MCwicGF0aCI6Ii8zOTkwOTYzNi8yOTgwODE2NzYtZTQxMDIxMTktZDE4Ny00YWI1LTgyOWEtYTUyNjk0NzhkZGNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDAzMDkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOTdlZTgwMzZlZWQ2NTM2OTM4ZGFhYjNkMGNkZmQ0NTY5NWFmYmU0NGFmYTdlNGZiYTQ5MzZiMTZlOGJiNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X7QxBKQeZe7nt1jG2-4r3og_hmb49SbuA110JHz49CE)

127.0.1.1? 127.0.1.1 your_host_name your_host_name ？  难道不是127.0.0.1吗

**Comment by MuziMin0222** [comment]
<img width="972" alt="image" src="https://github.com/dromara/CloudEon/assets/40995489/488643e4-9c1b-4d45-b56f-4cf28567aae5">
<img width="995" alt="image" src="https://github.com/dromara/CloudEon/assets/40995489/5fbd02ff-a801-4564-be6f-12a38230c0fe">

这是我的排查过程，发现master节点是不可以被调度的，所以我将zk替换成三台从节点，zk服务成功

**Comment by xlostpath** [comment]
你好，我是谢晋峰，你的邮件我已经收到，谢谢！

**Comment by MuziMin0222** [comment]
<img width="972" alt="image" src="https://github.com/dromara/CloudEon/assets/40995489/488643e4-9c1b-4d45-b56f-4cf28567aae5">
<img width="995" alt="image" src="https://github.com/dromara/CloudEon/assets/40995489/5fbd02ff-a801-4564-be6f-12a38230c0fe">

这是我的排查过程，发现master节点是不可以被调度的，所以我将zk替换成三台从节点，zk服务成功
